
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zepsf.c
OBJSC    = zepsf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepc
LOCDIR   = src/eps/interface/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
