
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lanczos.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = lanczos.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/lanczos/

include ${SLEPC_DIR}/bmake/slepc_common


