#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ipbasic.c ipdot.c iporthog.c ipform.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ipbasic.o ipdot.o iporthog.o ipform.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = IP
LOCDIR   = src/ip

include ${SLEPC_DIR}/conf/slepc_common
