ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ipbasic.c ipdot.c iporthog.c ipform.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ipbasic.o ipdot.o iporthog.o ipform.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = IP
LOCDIR   = src/ip

include ${SLEPC_DIR}/bmake/slepc_common
