
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svdregis.c svdbasic.c svdopts.c svdsetup.c svdsolve.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = svdregis.o svdbasic.o svdopts.o svdsetup.o svdsolve.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/interface/

include ${SLEPC_DIR}/bmake/slepc_common


