
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = eigensolver.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = eigensolver.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/eigensolver/

include ${SLEPC_DIR}/bmake/slepc_common


