
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = zslepc_start.c zslepc_startf.c zeps.c zst.c
SOURCEF  = slepcfort.F
SOURCEH  = 
OBJSC    = zslepc_start.o zslepc_startf.o zeps.o zst.o
OBJSF    = slepcfort.o
LIBBASE  = libslepcfortran
MANSEC   = 
LOCDIR   = src/fortran/custom/

include ${SLEPC_DIR}/bmake/slepc_common

