
ALL: lib

CFLAGS   = -DSLEPC_LIB_DIR='"${SLEPC_LIB_DIR}"'
FFLAGS   =
SOURCEC  = zslepc_start.c zslepc_startf.c zeps.c zst.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = zslepc_start.o zslepc_startf.o zeps.o zst.o
OBJSF    = 
LIBBASE  = libslepcfortran
MANSEC   = 
LOCDIR   = src/fortran/custom/

include ${SLEPC_DIR}/bmake/slepc_common

