
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = arnoldi.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = arnoldi.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/arnoldi/

include ${SLEPC_DIR}/bmake/slepc_common


