
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = trlanczos.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = trlanczos.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/lanczos/

include ${SLEPC_DIR}/bmake/slepc_common


