
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shift.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = shift.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/shift/

include ${SLEPC_DIR}/bmake/slepc_common


