
ALL: lib

#requirespackage  'PETSC_HAVE_HYPRE'
#requiresprecision double
#requiresscalar    real

CFLAGS   =
FFLAGS   =
SOURCEC  = lobpcg.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = lobpcg.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/lobpcg/

include ${SLEPC_DIR}/bmake/slepc_common


