#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2013, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#     
#  SLEPc is free software: you can redistribute it and/or modify it under  the
#  terms of version 3 of the GNU Lesser General Public License as published by
#  the Free Software Foundation.
#
#  SLEPc  is  distributed in the hope that it will be useful, but WITHOUT  ANY 
#  WARRANTY;  without even the implied warranty of MERCHANTABILITY or  FITNESS 
#  FOR  A  PARTICULAR PURPOSE. See the GNU Lesser General Public  License  for 
#  more details.
#
#  You  should have received a copy of the GNU Lesser General  Public  License
#  along with SLEPc. If not, see <http://www.gnu.org/licenses/>.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

#requiresdefine   'PETSC_USING_F90'

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = slepc.h slepceps.h slepcst.h slepcsvd.h slepcqep.h slepcpep.h slepcnep.h slepcmfn.h slepcip.h slepcds.h slepcfn.h \
            slepc.h90 slepceps.h90 slepcst.h90 slepcsvd.h90 slepcqep.h90 slepcpep.h90 slepcnep.h90 slepcmfn.h90 slepcip.h90 slepcds.h90 slepcfn.h90 \
            slepcdef.h slepcepsdef.h slepcstdef.h slepcsvddef.h slepcqepdef.h slepcpepdef.h slepcnepdef.h slepcmfndef.h slepcipdef.h slepcdsdef.h slepcfndef.h
LIBBASE   = libslepc
DIRS      = 
MANSEC    = 
LOCDIR    = include/finclude/

include ${SLEPC_DIR}/conf/slepc_common

runexamples:




