
CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = slepc.h slepceps.h slepcst.h
OBJSC     =
OBJSF     =
LIBBASE   = libslepc
DIRS      = 
MANSEC    = 
LOCDIR    = include/finclude/

include ${SLEPC_DIR}/bmake/slepc_common

runexamples:




