#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCEF   =
SOURCEH   = slepc.h slepceps.h slepcst.h slepcsvd.h slepcip.h
OBJSC     =
OBJSF     =
LIBBASE   = libslepc
DIRS      = 
MANSEC    = 
LOCDIR    = include/finclude/

include ${SLEPC_DIR}/bmake/slepc_common

runexamples:




