
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rqi.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = rqi.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/rqi/

include ${SLEPC_DIR}/bmake/slepc_common


