
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zipf.c
OBJSC    = zipf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepc
LOCDIR   = src/ip/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
