#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

SOURCEH  = stimpl.h ../../include/slepcst.h
DIRS     = interface impls
LOCDIR   = src/st/
MANSEC   = ST

include ${SLEPC_DIR}/bmake/slepc_common


