
ALL: lib

LIBBASE  = libslepc
DIRS     = power subspace arnoldi lanczos krylovschur lapack arpack blzpack planso trlan lobpcg primme
LOCDIR   = src/eps/impls/
MANSEC   = EPS

include ${SLEPC_DIR}/bmake/slepc_common


