
ALL: lib

LIBBASE  = libslepc
DIRS     = power subspace arnoldi lanczos krylovschur lapack arpack blzpack trlan blopex primme
LOCDIR   = src/eps/impls/
MANSEC   = EPS

include ${SLEPC_DIR}/bmake/slepc_common


