#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

LIBBASE  = libslepc
DIRS     = power subspace arnoldi lanczos krylovschur lapack arpack blzpack trlan blopex primme
LOCDIR   = src/eps/impls/
MANSEC   = EPS

include ${SLEPC_DIR}/conf/slepc_common


