
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = arnoldi2.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = arnoldi2.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/arnoldi2/

include ${SLEPC_DIR}/bmake/slepc_common


