
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zshell.c
OBJSC    = zshell.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepcfortran
LOCDIR   = src/st/impls/shell/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
