
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sinvert.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = sinvert.o 
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/sinvert/

include ${SLEPC_DIR}/bmake/slepc_common


