
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = sinvert.c shellmat.c
SOURCEF  = 
SOURCEH  = sinvert.h
OBJSC    = sinvert.o shellmat.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/sinvert/

include ${SLEPC_DIR}/bmake/slepc_common


