
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = none.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = none.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/none/

include ${SLEPC_DIR}/bmake/slepc_common


