#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zprimmef.c
OBJSC    = zprimmef.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepc
LOCDIR   = src/eps/impls/primme/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
