#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  = sinvert.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
DIRS     =
MANSEC   = ST
LOCDIR   = src/sys/classes/st/impls/sinvert/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
