
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = krylovschur.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = krylovschur.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/krylovschur/

include ${SLEPC_DIR}/bmake/slepc_common


