
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = power.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = power.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/power/

include ${SLEPC_DIR}/bmake/slepc_common


