#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

#requirespackage  'SLEPC_HAVE_ARPACK'

CFLAGS   =
FFLAGS   =
SOURCEC  = arpack.c
SOURCEF  = 
SOURCEH  = arpackp.h
OBJSC    = arpack.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/arpack/

include ${SLEPC_DIR}/conf/slepc_common


