
ALL: lib

#requirespackage  'SLEPC_HAVE_ARPACK'

CFLAGS   =
FFLAGS   =
SOURCEC  = arpack.c
SOURCEF  = 
SOURCEH  = arpackp.h
OBJSC    = arpack.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/arpack/

include ${SLEPC_DIR}/bmake/slepc_common


