#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  = interpol.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcnep
DIRS     =
MANSEC   = NEP
LOCDIR   = src/nep/impls/interpol/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
