
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svdlapack.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = svdlapack.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/lapack/

include ${SLEPC_DIR}/bmake/slepc_common


