
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = subspace.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = subspace.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/subspace/

include ${SLEPC_DIR}/bmake/slepc_common


