
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cayley.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = cayley.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/cayley/

include ${SLEPC_DIR}/bmake/slepc_common


