#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  = gklanczos.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsvd
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/lanczos/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
