#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#requirespackage 'PETSC_HAVE_MAGMA'

SOURCEC  = slepcmagma.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
MANSEC   = sys
LOCDIR   = src/sys/magma/
DIRS     =

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
