
ALL: lib

#requirespackage   'SLEPC_HAVE_PLANSO'
#requiresscalar    real

CFLAGS   =
FFLAGS   =
SOURCEC  = planso.c
SOURCEF  = 
SOURCEH  = plansop.h
OBJSC    = planso.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/planso/

include ${SLEPC_DIR}/bmake/slepc_common


