
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dlregis.c monitor.c basic.c default.c itregis.c opts.c setup.c solve.c orthog.c dense.c mem.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = dlregis.o monitor.o basic.o default.o itregis.o opts.o setup.o solve.o orthog.o dense.o mem.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/interface/

include ${SLEPC_DIR}/bmake/slepc_common


