#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = monitor.c basic.c default.c itregis.c opts.c setup.c solve.c dense.c mem.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = monitor.o basic.o default.o itregis.o opts.o setup.o solve.o dense.o mem.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/interface/

include ${SLEPC_DIR}/conf/slepc_common


