
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cross.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = cross.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/cross/

include ${SLEPC_DIR}/bmake/slepc_common
