
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cyclic.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = cyclic.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = SVD
LOCDIR   = src/svd/impls/cyclic/

include ${SLEPC_DIR}/bmake/slepc_common
