#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  = davidson.c dvdcalcpairs.c dvdimprovex.c dvdinitv.c dvdschm.c dvdtestconv.c dvdupdatev.c dvdutils.c dvdgd2.c
SOURCEH  = davidson.h
LIBBASE  = libslepceps
DIRS     = gd jd
MANSEC   = EPS

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
