#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#requiresscalar    real

SOURCEC  = dibtdc.c dlaed3m.c dmerg2.c dsbtdc.c dsrtdf.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
DIRS     =
MANSEC   = DS
LOCDIR   = src/sys/classes/ds/impls/hep/bdc/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
