
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fold.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = fold.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/fold/

include ${SLEPC_DIR}/bmake/slepc_common


