#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

LOCDIR     = src/sys/classes/fn/tests/
MANSEC     = FN
TESTS      = test1 test1f test2 test3 test4 test5 test6 test7 test7f test8 test9 test10 test11 test12 test13

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
