
ALL: lib

#requirespackage  'SLEPC_HAVE_BLZPACK'
#requiresscalar   real

CFLAGS   =
FFLAGS   =
SOURCEC  = blzpack.c
SOURCEF  = 
SOURCEH  = blzpackp.h
OBJSC    = blzpack.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/blzpack/

include ${SLEPC_DIR}/bmake/slepc_common


