
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = shell.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = shell.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/impls/shell/

include ${SLEPC_DIR}/bmake/slepc_common


