
#requiresscalar real 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = srrit.c laqr3.c dcond.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = srrit.o laqr3.o dcond.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/srrit/

include ${SLEPC_DIR}/bmake/slepc_common


