
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = srrit.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = srrit.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/srrit/

include ${SLEPC_DIR}/bmake/slepc_common


