#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEH  = ../../../../include/slepc/private/bvimpl.h ../../../../include/slepcbv.h
DIRS     = interface impls tests f90-mod
LOCDIR   = src/sys/classes/bv/
MANSEC   = BV

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
