#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     SLEPc - Scalable Library for Eigenvalue Problem Computations
#     Copyright (c) 2002-2007, Universidad Politecnica de Valencia, Spain
#
#     This file is part of SLEPc. See the README file for conditions of use
#     and additional information.
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

SOURCEH  = svdimpl.h ../../include/slepcsvd.h
DIRS     = interface impls
LOCDIR   = src/svd/
MANSEC   = SVD

include ${SLEPC_DIR}/conf/slepc_common


