#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

LOCDIR     = src/svd/tests/
MANSEC     = SVD
TESTS      = test1 test2 test3 test4 test4f test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test18

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
