
ALL: lib

#requirespackage   'SLEPC_HAVE_PRIMME'

CFLAGS   = ${PRIMME_FLAGS}
FFLAGS   =
SOURCEC  = primmes.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = primmes.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/primme/

include ${SLEPC_DIR}/bmake/slepc_common


