
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = slepc.h slepceps.h slepcst.h slepclog.h slepcversion.h slepcblaslapack.h
OBJSC    =
OBJSF    =
LIBBASE  = libslepc
DIRS     = finclude
LOCDIR   = include/
MANSEC   = 

include ${SLEPC_DIR}/bmake/slepc_common

runexamples:



