
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = stfunc.c stset.c stsolve.c stsles.c stregis.c shellmat.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = stfunc.o stset.o stsolve.o stsles.o stregis.o shellmat.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = ST
LOCDIR   = src/st/interface/

include ${SLEPC_DIR}/bmake/slepc_common


