#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  = bvmat.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
DIRS     =
MANSEC   = BV
LOCDIR   = src/sys/classes/bv/impls/mat/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
