
ALL: lib

#requirespackage   'SLEPC_HAVE_TRLAN'
#requiresscalar    real

CFLAGS   =
FFLAGS   =
SOURCEC  = trlan.c
SOURCEF  = 
SOURCEH  = trlanp.h
OBJSC    = trlan.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/trlan/

include ${SLEPC_DIR}/bmake/slepc_common


