
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = 
DOCS     = 
OBJSC    =
OBJSF    =
LIBBASE  = libslepc
LINCLUDE = ${SOURCEH}
DIRS     = 
LOCDIR   = docs/

include ${SLEPC_DIR}/bmake/slepc_common

runexamples:

