#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

LOCDIR     = src/sys/classes/st/tests/
MANSEC     = ST
TESTS      = test1 test2 test3 test4 test5 test6 test7 test8 test9

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
