
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zsvdf.c
OBJSC    = zsvdf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepc
LOCDIR   = src/svd/interface/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
