
ALL: lib


CFLAGS   =
FFLAGS   =
SOURCEF	 = 
SOURCEH	 = 
OBJSC	 = ${SOURCEC:.c=.o}
OBJSF	 =
LIBBASE	 = libslepcfortran
MANSEC	 = 
LOCDIR   = src/fortran/auto/

include makefile.src
include ${SLEPC_DIR}/bmake/slepc_common

