#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

SOURCEC  =
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
MANSEC   = sys
LOCDIR   = src/sys/classes/
DIRS     = fn ds bv st rg

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
