
#requirespackage   'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS   =
FFLAGS   =
SOURCEC  = zstf.c
OBJSC    = zstf.o
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libslepcfortran
LOCDIR   = src/st/interface/ftn-custom/
include ${SLEPC_DIR}/bmake/slepc_common  
