
ALL: lib

#requirespackage  'PETSC_HAVE_BLOPEX'
#requiresprecision double
#requiresscalar    real

CFLAGS   = ${BLOPEX_INCLUDE}
FFLAGS   =
SOURCEC  = blopex.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = blopex.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/blopex/

include ${SLEPC_DIR}/bmake/slepc_common


