
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lapack.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = lapack.o
LIBBASE  = libslepc
DIRS     =
MANSEC   = EPS
LOCDIR   = src/eps/impls/lapack/

include ${SLEPC_DIR}/bmake/slepc_common


